### ISSUE TITLE
Trigger a merge

### ISSUE THREAD

**Issue by albertvipe** [topicusfinan/bitbucket-webhooks-plugin#31]
Hello,

I've this plugin configured and using against Jenkins. It's working well except when I made a merge and the target branch job is not triggered automatically.
There is a way to achieve that?

Thank you!

**Comment by burnettk** [comment]
yeah, we actually downgraded https://marketplace.atlassian.com/plugins/nl.topicus.bitbucket.bitbucket-webhooks/versions from 1.3.0 to 1.2.0 to fix this. 1.3.0 doesn't seem to send the "new" commit information on merges (1.2.0 doesn't send any of that info, so it seems like jenkins just looks it up, which at least works, even if it's not quite as fast as it could be with the new hotness in 1.3.0).

we're using Bitbucket Server v4.14.3.

**Comment by emeagher** [comment]
We are experiencing the same issue. I'm going to try downgrading.

**Comment by albertvipe** [comment]
I've just made the downgrade to the 1.2.0 as a workaround and anything have changed.
Note that I'm using Bitbucket Server v4.11.1.

@emeagher, could you try it?

Maybe @Eernie can tell us if we're doing something wrong.

**Comment by emeagher** [comment]
@albertvipe I tried it last night and it appears to be working.

**Comment by dongo0223** [comment]
We faced with that problem a couple of days ago. 
It looks like the repoChanged method is not called after the merge. Based on Bitbucket server API documentation this is the correct behavior.
https://github.com/topicusfinan/bitbucket-webhooks-plugin/blob/master/src/main/java/nl/topicus/bitbucket/api/PullRequestListener.java#L118

`public void repoChangedEvent(AbstractRepositoryRefsChangedEvent event)`

https://developer.atlassian.com/static/javadoc/bitbucket-server/4.14.4/api/reference/com/atlassian/bitbucket/event/repository/RepositoryPushEvent.html

> Listeners that are interested in all ref changes, not just those stemming from pushes (such as pull request merges), should listen for RepositoryRefsChangedEvents instead.

So I replaced the AbstractRepositoryRefsChangedEvent listener to RepositoryRefsChangedEvents and it seems to be working.

**Comment by burnettk** [comment]
@dongo0223 , it sounds like you have a local modification that you're already using. can you submit a pull request?

**Comment by dongo0223** [comment]
@burnettk yes, I've created a PR #32

**Comment by abishek3876** [comment]
Hi Guys,
A downstream change in bitbucket-branch-source plugin was created and released. Did you guys also update that plugin? The latest versions of both the plugins seem to work well on merges together atleast for me.

**Comment by casz** [comment]
Yes, I have. Yet I had developers complains about PR merged was not working and had to lower the scan interval 👎

**Comment by burnettk** [comment]
@abishek3876 yes, we tried updating the bitbucket branch source plugin to newest and got the same result.

**Comment by dongo0223** [comment]
I think the bitbucket-webhooks-plugin should work like the bitbucket cloud webhooks. Currently, this is not true because there is no repo:push event after merge. It seemingly worked before #25 because there was a pr:updated event instead of pr:fulfilled and that event triggered a repo reindex in bitbucket-branch-source plugin. 
https://github.com/jenkinsci/bitbucket-branch-source-plugin/blob/master/src/main/java/com/cloudbees/jenkins/plugins/bitbucket/hooks/PullRequestHookProcessor.java#L82

Now, the pr:fulfilled event handled as REMOVED event type:
https://github.com/jenkinsci/bitbucket-branch-source-plugin/blob/master/src/main/java/com/cloudbees/jenkins/plugins/bitbucket/hooks/PullRequestHookProcessor.java#L79

The bitbucket-branch-source plugin is using the same hook processor for bitbucket cloud and server.
